### ISSUE TITLE
query() needs to support an arbitrary number of terms

### ISSUE THREAD

**Issue by eaceaser** [faunadb/faunadb-python#38]
You can put an array of queries into a query. Its not really well documented ATM (which should probably be a separate issue) but see

https://faunadb.com/documentation/queries#read_functions

under Get, there is a section for multi-gets that shows the syntax.

**Comment by eaceaser** [comment]
nvm you can just pass an array in

**Comment by ashfire908** [comment]
We could still update it to take either a list or `*args`.

**Comment by evan** [comment]
If the service doesn't take varargs I don't think the client needs to.
